export enum Routes {
  AUTH = 'auth',
  USERS = 'users',
  CONVERSATIONS = 'conversations',
  PARTICIPANTS = 'participants',
  MESSAGES = 'messages',
  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  CONVERSATIONS = 'CONVERSATIONS_SERVICE',
  PARTICIPANTS = 'PARTICIPANTS_SERVICE',
  MESSAGES = 'MESSAGE_SERVICE',
  GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
}
